defaults:
  - _self_
  - augmentations: reconstruction.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mae-tissuemnist" # change here for tissuemnist
method: "nnclr"
nnclr2: False
log_path: "/home/mila/f/feiziaar/scratch/ht-image-ssl/logs/"
backbone:
  name: "vit_small"
  kwargs:
    patch_size: 16
    img_size: 224
method_kwargs:
  decoder_embed_dim: 512
  decoder_depth: 8
  decoder_num_heads: 16
  mask_ratio: 0.75
  norm_pix_loss: True
data:
  dataset: tissuemnist # change here for tissuemnist
  train_path: "/home/mila/f/feiziaar/scratch/tissuemnist/"
  val_path: "/home/mila/f/feiziaar/scratch/tissuemnist/"
  format: "image_folder"
  num_workers: 10
optimizer:
  name: "adamw"
  batch_size: 256
  lr: 2.0e-4
  classifier_lr: 2.0e-4
  weight_decay: 0.05
  kwargs:
    betas: [0.9, 0.95]
scheduler:
  name: "warmup_cosine"
checkpoint_config:
  enabled: False
  dir: "/home/mila/f/feiziaar/scratch/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
test: True