defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "nnsiam-tissuemnist" # change here for tissuemnist
method: "nnsiam"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  pred_hidden_dim: 4096
  proj_output_dim: 2048
  queue_size: 65536
momentum:
  base_tau: 0.99
  final_tau: 1.0
data:
  dataset: tissuemnist # change here for tissuemnist
  train_path: "./datasets"
  val_path: "./datasets"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.5
  classifier_lr: 0.1
  weight_decay: 1e-5
scheduler:
  name: "warmup_cosine"
checkpoint_config:
  enabled: False
  dir: "/home/mila/f/feiziaar/scratch/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16