name: resnet101
train: false
epochs: 0
loss: 'mse'
opt: 'adam'
sizes: []
input_size: 224
lr: 1e-3
weight_decay: 1e-5
random_ids: [100, 200, 300, 500, 600, 700, 800, 900, 1200, 1500, 1900, 2000]
transform: 'noTransform'