defaults:
  - _self_
  - augmentations: reconstruction.yaml
  - nn_augmentations: no_transform.yaml
  - emb_model: resnet50.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "deepclusterv2-country211"
method: "deepclusterv2"
nnclr2: True
nn_key: "feats"
log_path: "/network/scratch/f/feiziaar/ht-image-ssl/logs/"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 128
  num_prototypes: [3000, 3000, 3000]
data:
  dataset: country211
  train_path: "/network/scratch/f/feiziaar/country211/train"
  val_path: "/network/scratch/f/feiziaar/country211/val"
  format: "image_folder"
  num_workers: 10
  num_nns_choice: 1
  num_nns: 1
  filter_sim_matrix: False
  reload_freq: 0
  emb_path: ''
  pin_memory: True
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.6
  classifier_lr: 0.1
  weight_decay: 1e-6
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
  min_lr: 0.0006
  warmup_start_lr: 0.0
  warmup_epochs: 11
checkpoint_config:
  enabled: True
  dir: "/network/scratch/f/feiziaar/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: True
dali:
  encode_indexes_into_labels: True

# overwrite PL stuff
max_epochs: 400
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
test: True