defaults:
  - _self_
  - augmentations: reconstruction.yaml
  - nn_augmentations: no_transform.yaml
  - emb_model: resnet50.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mocov3-vit-country211"
method: "mocov3"
backbone:
  name: "vit_small"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
  temperature: 0.2
momentum:
  base_tau: 0.99
  final_tau: 1.0
data:
  dataset: country211
  train_path: "/network/scratch/f/feiziaar/country211/train"
  val_path: "/network/scratch/f/feiziaar/country211/val"
  format: "image_folder"
  num_workers: 10
  num_nns_choice: 1
  num_nns: 1
  filter_sim_matrix: False
  reload_freq: 0
  emb_path: ''
  pin_memory: True
optimizer:
  name: "adamw"
  batch_size: 256
  lr: 3.0e-4
  classifier_lr: 3.0e-4
  weight_decay: 0.1
scheduler:
  name: "warmup_cosine"
checkpoint_config:
  enabled: True
  dir: "/network/scratch/f/feiziaar/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 400
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
test: True