defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - nn_augmentations: reconstruction.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "barlow_twins-hotels50k-test" # change here for cifar10
method: "barlow_twins"
log_path: "/home/mila/f/feiziaar/scratch/ht-image-ssl/logs/"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  scale_loss: 0.1
data:
  dataset: hotels50k-test
  train_path: "../hotels50k_maxEdge500_restructured/trainval"
  val_path: "../hotels50k_maxEdge500_restructured/test1"
  format: "image_folder"
  num_workers: 10
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint_config:
  enabled: True
  dir: "/home/mila/f/feiziaar/scratch/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16