defaults:
  - _self_
  - augmentations: reconstruction.yaml
  - nn_augmentations: no_transform.yaml
  - emb_model: resnet50.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "dino-vit-imagenet100"
method: "dino"
backbone:
  name: "vit_tiny"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  num_prototypes: 65536
  norm_last_layer: False
momentum:
  base_tau: 0.9995
  final_tau: 1.0
data:
  dataset: imagenet100
  train_path: "/network/scratch/f/feiziaar/imagenet-100/train"
  val_path: "/network/scratch/f/feiziaar/imagenet-100/val"
  format: "image_folder"
  num_workers: 10
  num_nns_choice: 1
  num_nns: 1
  filter_sim_matrix: False
  reload_freq: 0
  emb_path: ''
optimizer:
  name: "adamw"
  batch_size: 128
  lr: 0.005
  classifier_lr: 3e-3
  weight_decay: 1e-4
scheduler:
  name: "warmup_cosine"
  warmup_start_lr: 0.00001
checkpoint_config:
  enabled: True
  dir: "/network/scratch/f/feiziaar/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 400
devices: [0, 1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16