defaults:
  - _self_
  - emb_model: resnet50.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "vicreg-inat" # change here for inat
method: "vicreg"
nnclr2: False
nn_key: 'feats'
log_path: "../../scratch/ht-image-ssl/logs/"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  sim_loss_weight: 25.0
  var_loss_weight: 25.0
  cov_loss_weight: 1.0
data:
  dataset: inat18 # change here for inat
  data_path: "/home/mila/f/feiziaar/scratch/inat18/"
  train_path: "/home/mila/f/feiziaar/scratch/inat18/train2018.json"
  val_path: "/home/mila/f/feiziaar/scratch/inat18/val2018.json"
  format: "image_folder"
  num_workers: 4
  num_nns_choice: 1
  num_nns: 1
  reload_freq: 0
  filter_sim_matrix: False
  subsample_by: 1
augmentations:
  - rrc:
      enabled: True
      crop_min_scale: 0.2
      crop_max_scale: 1.0
    color_jitter:
      enabled: True
      brightness: 0.4
      contrast: 0.4
      saturation: 0.2
      hue: 0.1
      prob: 0.8
    grayscale:
      enabled: True
      prob: 0.2
    gaussian_blur:
      enabled: True
      prob: 0.0
    solarization:
      enabled: True
      prob: 0.1
    equalization:
      enabled: True
      prob: 0.0
    horizontal_flip:
      enabled: True
      prob: 0.5
    crop_size: 32
    num_crops: 2
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint_config:
  enabled: False
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16