defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - augmentations: reconstruction.yaml
  - nn_augmentations: no_transform.yaml
  - emb_model: resnet50.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "barlow_twins-tinyimagenet"
method: "barlow_twins"
nnclr2: True
nn_key: "feats"
log_path: "/network/scratch/f/feiziaar/ht-image-ssl/logs/"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 4096
  lamb: 0.0051
  scale_loss: 0.048
data:
  dataset: imagenet
  train_path: "/network/scratch/f/feiziaar/tinyimagenet/tiny-tinyimagenet-200/train"
  val_path: "/network/scratch/f/feiziaar/tinyimagenet/tiny-tinyimagenet-200/val"
  format: "image_folder"
  num_workers: 10
  num_nns_choice: 1
  num_nns: 1
  filter_sim_matrix: False
  reload_freq: 0
  emb_path: ''
optimizer:
  name: "lars"
  batch_size: 512
  lr: 0.8
  classifier_lr: 0.1
  weight_decay: 1.5e-6
  kwargs:
    clip_lr: False
    eta: 0.001
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint_config:
  enabled: True
  dir: "/network/scratch/f/feiziaar/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0, 1, 2, 3]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
test: True