defaults:
  - _self_
  - augmentations: reconstruction.yaml
  - nn_augmentations: no_transform.yaml
  - emb_model: resnet50.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "vicreg-tinyimagenet" # change here for cifar10
method: "vicreg"
nnclr2: True
nn_key: "feats"
log_path: "/network/scratch/f/feiziaar/ht-image-ssl/logs/"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  sim_loss_weight: 25.0
  var_loss_weight: 25.0
  cov_loss_weight: 1.0
data:
  dataset: tinyimagenet
  train_path: "/network/scratch/f/feiziaar/tinyimagenet/tiny-imagenet-200/train"
  val_path: "/network/scratch/f/feiziaar/tinyimagenet/tiny-imagenet-200/val"
  format: "image_folder"
  num_workers: 10
  num_nns_choice: 1
  num_nns: 1
  filter_sim_matrix: False
  reload_freq: 0
  emb_path: ''
augmentations:
  - rrc:
      enabled: True
      crop_min_scale: 0.2
      crop_max_scale: 1.0
    color_jitter:
      enabled: True
      brightness: 0.4
      contrast: 0.4
      saturation: 0.2
      hue: 0.1
      prob: 0.8
    grayscale:
      enabled: True
      prob: 0.2
    gaussian_blur:
      enabled: True
      prob: 0.0
    solarization:
      enabled: True
      prob: 0.1
    equalization:
      enabled: True
      prob: 0.0
    horizontal_flip:
      enabled: True
      prob: 0.5
    crop_size: 32
    num_crops: 2
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint_config:
  enabled: True
  dir: "/network/scratch/f/feiziaar/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
test: True