defaults:
  - _self_
  - augmentations: reconstruction.yaml
  - wandb: private.yaml
  - emb_model: resnet50.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "byol-hotelid-val" # change here for cifar10
method: "byol"
nnclr2: True
log_path: "/home/mila/f/feiziaar/scratch/ht-image-ssl/logs/"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
momentum:
  base_tau: 0.99
  final_tau: 1.0
data:
  dataset: hotelid-val
  train_path: "/home/mila/f/feiziaar/scratch/hotelid-2021_maxEdge500_restructured/train"
  val_path: "/home/mila/f/feiziaar/scratch/hotelid-2021_maxEdge500_restructured/val1"
  val2_path: "/home/mila/f/feiziaar/scratch/hotelid-2021_maxEdge500_restructured/val2"
  val3_path: "/home/mila/f/feiziaar/scratch/hotelid-2021_maxEdge500_restructured/val3"
  format: "image_folder"
  num_workers: 10
  num_nns_choice: 1
optimizer:
  name: "lars"
  batch_size: 256
  lr: 1.0
  classifier_lr: 0.1
  weight_decay: 1e-5
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: False
  dir: "/home/mila/f/feiziaar/scratch/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 30
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16