defaults:
  - _self_
  - augmentations: reconstruction.yaml
  - emb_model: resnet50.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "nnclr-pathmnist-nnclr2" # change here for pathmnist0
method: "nnclr"
nnclr2: True
log_path: "/home/mila/f/feiziaar/scratch/ht-image-ssl/logs/"
backbone:
  name: "resnet18"
method_kwargs:
  temperature: 0.2
  proj_hidden_dim: 2048
  pred_hidden_dim: 4096
  proj_output_dim: 256
  queue_size: 65536
data:
  dataset: pathmnist # change here for pathmnist
  train_path: "/home/mila/f/feiziaar/scratch/pathmnist/"
  val_path: "/home/mila/f/feiziaar/scratch/pathmnist/"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.4
  classifier_lr: 0.1
  weight_decay: 1e-5
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint_config:
  enabled: False
  dir: "/home/mila/f/feiziaar/scratch/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16