defaults:
  - _self_
  - augmentations: reconstruction.yaml
  - nn_augmentations: no_transform.yaml
  - emb_model: resnet50.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mocov2plus-aircrafts" # change here for aircrafts0
method: "mocov2plus"
log_path: "/network/scratch/f/feiziaar/ht-image-ssl/logs/"
nn_key: 'feats'
nnclr2: Trues
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  queue_size: 32768
  temperature: 0.2
momentum:
  base_tau: 0.99
  final_tau: 0.999
data:
  dataset: aircrafts # change here for aircrafts0
  train_path: "/home/mila/f/feiziaar/scratch/aircrafts/"
  val_path: "/home/mila/f/feiziaar/scratch/aircrafts/"
  format: "image_folder"
  num_workers: 10
  num_nns: 1
  num_nns_choice: 1
  filter_sim_matrix: False
  reload_freq: 0
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.3
  classifier_lr: 0.3
  weight_decay: 1e-4
scheduler:
  name: "warmup_cosine"
checkpoint_config:
  enabled: False
  dir: "/network/scratch/f/feiziaar/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
test: True