defaults:
  - _self_
  - augmentations: reconstruction.yaml
  - nn_augmentations: no_transform.yaml
  - emb_model: resnet50.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mae-aircrafts" # change here for aircrafts
method: "mae"
nnclr2: False
nn_key: 'feats'
log_path: "/network/scratch/f/feiziaar/ht-image-ssl/logs/"
backbone:
  name: "vit_small"
  kwargs:
    patch_size: 4
    img_size: 32
method_kwargs:
  decoder_embed_dim: 512
  decoder_depth: 8
  decoder_num_heads: 16
  mask_ratio: 0.75
  norm_pix_loss: True
data:
  dataset: aircrafts # change here for aircrafts
  train_path: "/home/mila/f/feiziaar/scratch/aircrafts/"
  val_path: "/home/mila/f/feiziaar/scratch/aircrafts/"
  format: "image_folder"
  num_workers: 10
optimizer:
  name: "adamw"
  batch_size: 256
  lr: 2.0e-4
  classifier_lr: 2.0e-4
  weight_decay: 0.05
  kwargs:
    betas: [0.9, 0.95]
scheduler:
  name: "warmup_cosine"
checkpoint_config:
  enabled: False
  dir: "/network/scratch/f/feiziaar/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16