defaults:
  - _self_
  - augmentations: reconstruction.yaml
  - nn_augmentations: no_transform.yaml
  - emb_model: resnet50.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "barlow_twins-inat18-nnclr2" 
method: "barlow_twins"
nnclr2: True
nn_key: 'feats'
log_path: "/home/mila/f/feiziaar/scratch/ht-image-ssl/logs"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  scale_loss: 0.1
data:
  dataset: inat18 # change here for inat
  data_path: "/home/mila/f/feiziaar/scratch/inat18/"
  train_path: "/home/mila/f/feiziaar/scratch/inat18/train2018.json"
  val_path: "/home/mila/f/feiziaar/scratch/inat18/val2018.json"
  format: "image_folder"
  num_workers: 4
  filter_sim_matrix: False
  num_nns_choice: 1
  num_nns: 1
  reload_freq: 0
  subsample_by: 1
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint_config:
  enabled: False
  dir: "../../scratch/ht-image-ssl/trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16